location ~ /\.(?!well-known(?:/|$)) {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* ^/(?:README\.md|\.htaccess|wp-config\.php(?:\..*)?)$ {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* \.(?:bak|old|orig|save|swp|swo|tmp|temp|dist|sql)(?:~)?$ {
    deny all;
    access_log off;
    log_not_found off;
}
